baseURL: https://recipes.dayl.in
disablePathToLower: true
languageCode: en-us
title: Recipe Book
publishDir: docs

defaultcontentlanguage: en

canonifyurls: true
theme: "simple-recipe"

params:
  author: Daylin Morgan
  description: recipes for daylin and friends
  email: me@dayl.in
  keywords: 'recipes'
  favicon_32: /images/favicon-32x32.png
  favicon_16: /images/favicon-16x16.png
  help: true

menu:
  main:
    - name: Category
      weight: 1
      url: /category/
    - name: Cuisine
      weight: 2
      url: /cuisine/
    - name: Tags
      weight: 3
      url: /tags/

taxonomies:
  category: category
  cuisine: cuisine
  tag: tags
